apiVersion: v1
kind: Service
metadata: 
  name: knfolio-service
spec: 
  selector: 
    app: knfolio
  type: {{ .Values.service.type }}
  ports: 
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
