image:
  repository: cyrof/remotewakeserver
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 8000

hostNetwork: true
dnsPolicy: ClusterFirstWithHostNet

containerPort: 8000

env:
  broadcast: "192.168.68.255"
  port: 9
  devices: '{"pc":{"mac":"10-FF-E0-3B-AE-A4"}}'

auth:
  enabled: false
  existingSecret: ""
  existingSecretKey: "token"
  token: ""

ingress:
  enabled: true
  className: "nginx"
  host: "wol.cyrostack.arpa"
  path: "/"
  pathType: Prefix
  tls:
    enabled: false
    secretName: ""

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
